# Generated by Django 2.1.3 on 2018-11-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=300)),
                ('sale', models.CharField(choices=[('OPO', 'One Plus One'), ('TPO', 'Two Plus One'), ('OTR', 'Other')], max_length=3)),
            ],
        ),
    ]
